# Generated by Django 5.1.6 on 2025-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_category_alter_event_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
