# Generated by Django 5.1.6 on 2025-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="assets",
            field=models.ImageField(blank=True, null=True, upload_to="tasks_asset"),
        ),
    ]
