# Generated by Django 5.1.6 on 2025-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="assets",
            field=models.ImageField(blank=True, null=True, upload_to="events_asset"),
        ),
    ]
