# Generated by Django 5.1.6 on 2025-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="assets",
            field=models.ImageField(
                blank=True,
                default="events_asset/default.jpg",
                null=True,
                upload_to="events_asset",
            ),
        ),
    ]
